#Turn StructureNerfer off.
disable-plugin: false


#################
#Nerf Structures#
#################

#Note: read the README for information on how to use this file: https://github.com/lichenaut/LiminalMod/blob/master/README.md

#Example:
#VILLAGE_PLAINS:
#  spawn-rate: 50
#  abandoned-rate: 75

structures:
  ANCIENT_CITY:
  BASTION_REMNANT:
  BURIED_TREASURE:
  DESERT_PYRAMID:
  END_CITY:
  FORTRESS:
  IGLOO:
  JUNGLE_PYRAMID:
  MANSION:
  MINESHAFT:
  MINESHAFT_MESA:
  MONUMENT:
  OCEAN_RUIN_COLD:
  OCEAN_RUIN_WARM:
  PILLAGER_OUTPOST:
  RUINED_PORTAL:
  RUINED_PORTAL_DESERT:
  RUINED_PORTAL_JUNGLE:
  RUINED_PORTAL_MOUNTAIN:
  RUINED_PORTAL_NETHER:
  RUINED_PORTAL_OCEAN:
  RUINED_PORTAL_SWAMP:
  SHIPWRECK:
  SHIPWRECK_BEACHED:
  STRONGHOLD:
  SWAMP_HUT:
  TRAIL_RUINS:
  VILLAGE_DESERT:
  VILLAGE_PLAINS:
  VILLAGE_SAVANNA:
  VILLAGE_SNOWY:
  VILLAGE_TAIGA:


###############
#Miscellaneous#
###############

#Set patrol spawn rate.
patrol-spawn-rate: 100

#Set Piglin spawn rate.
  #Does not change the piglin count limit, only changes the rate at which the count grows.
piglin-spawn-rate: 100
  #Consider also editing spawn limits, spawn ranges, and spawn timings in your server's files: "bukkit.yml", "spigot.yml", and "paper.yml", etc...

#Wandering Trader spawn rate.
wandering-trader-spawn-rate: 100


###################
#Abandonment Speed#
###################

#In order to "abandon" a structure, LiminalMod will sometimes load a structure's chunks.
#The following setting is the amount of time, in ticks, this plugin will wait before loading another chunk.
#Think of this as trying to fit a Slime through a tunnel, where the tunnel is the server's processing power. One would want to stretch the slime just enough to fit.

#Too low, and the server will try to load a lot of chunks at once and lag. Too high, and the structure will take a long time to process, also wasting time.
ticks-per-chunk: 10