// automatically generated by the FlatBuffers compiler, do not modify

package com.lichenaut.liminalmod.load.LiminalMod;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LMStructureData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static LMStructureData getRootAsLMStructureData(ByteBuffer _bb) { return getRootAsLMStructureData(_bb, new LMStructureData()); }
  public static LMStructureData getRootAsLMStructureData(ByteBuffer _bb, LMStructureData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LMStructureData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String structure() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer structureAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer structureInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean abandoned() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createLMStructureData(FlatBufferBuilder builder,
      int structureOffset,
      boolean abandoned) {
    builder.startTable(2);
    LMStructureData.addStructure(builder, structureOffset);
    LMStructureData.addAbandoned(builder, abandoned);
    return LMStructureData.endLMStructureData(builder);
  }

  public static void startLMStructureData(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addStructure(FlatBufferBuilder builder, int structureOffset) { builder.addOffset(0, structureOffset, 0); }
  public static void addAbandoned(FlatBufferBuilder builder, boolean abandoned) { builder.addBoolean(1, abandoned, false); }
  public static int endLMStructureData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LMStructureData get(int j) { return get(new LMStructureData(), j); }
    public LMStructureData get(LMStructureData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

